title:  Sohrab Saeb
author:
  name:
  twitter:  sosata

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname:

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/sosata'}
- {icon: 'twitter', link: 'https://twitter.com/sosata'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/sohrobst/'}
- {icon: 'envelope', link: 'mailto:ss@kernel.co'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
